// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package details

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "bca-go-final/internal/views/components"
import "bca-go-final/internal/types"

func concat(a, b string) string {
	return a + b
}

func EditDetails(budgetItems []types.Select, invoiceId string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(concat(concat("/bca/partials/invoices/", invoiceId), "/details")))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-trigger=\"submit\" hx-target=\"#invoice-details\" hx-swap=\"innerHTML\" hx-on=\"htmx:afterRequest: htmxHandleDetailsError(event)\"><div class=\"flex flex-col h-full gap-8\"><div id=\"details-error\" class=\"text-red-500 text-sm\"></div><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.DrawerTitle("Agregar Detalles").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.SelectComponent(budgetItems, "Seleccione una Partida", "item", "item", "", "Partida").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("text", "Cantidad", "quantity", "quantity", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("text", "Costo", "cost", "cost", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Input("text", "Total", "detailtotal", "detailtotal", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ButtonGroup().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></form><script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `
         var quantity = document.getElementById("quantity")
         var cost = document.getElementById("cost")
         var detailTotal = document.getElementById("detailtotal")
         var b = document.getElementById("save-button")

         detailTotal.disabled = true

         quantity.addEventListener("input", calculateTotal)
         cost.addEventListener("input", calculateTotal)

         function htmxHandleDetailsError(event) {
              document.getElementById("details-error").innerHTML = ""
              if (event.detail.xhr.status >= 400) {
                   document.getElementById("details-error").innerHTML = event.detail.xhr.response
              }
         }

         function calculateTotal() {
              let q = quantity.value === "" ? 0 : parseFloat(quantity.value)
              let c = cost.value === "" ? 0 : parseFloat(cost.value)
              
              if (isNaN(q)) {
                   detailTotal.classList.add("error-border")
                   quantity.classList.add("error-border")
                   q = 0
                   detailTotal.value = "0.00"
                   b.disabled = true
                   return
              }
              if (isNaN(c)) {
                   detailTotal.classList.add("error-border")
                   cost.classList.add("error-border")
                   c = 0
                   detailTotal.value = "0.00"
                   b.disabled = true
                   return
              }


              detailTotal.classList.remove("error-border")
              quantity.classList.remove("error-border")
              cost.classList.remove("error-border")
              b.disabled = false

              detailTotal.value = (q * c).toLocaleString(2)
         }

         function resetClose() {
              closeDrawer()
         }
    `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
