// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package icons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BudgetItemIcon() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg enable-background=\"new 0 0 48 48\" height=\"15\" id=\"Layer_3\" version=\"1.1\" viewBox=\"0 0 48 48\" width=\"15\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g><rect fill=\"#90a4ae\" height=\"6\" width=\"24\" x=\"16\" y=\"3\"></rect> <polygon fill=\"#90a4ae\" points=\"8,0 4,0 4,4.001 0,4.001 0,8.001 4,8.001 4,12 8,12 8,8.001 12,8.001 12,4.001 8,4.001  \"></polygon> <polygon fill=\"#90a4ae\" points=\"8,18 4,18 4,22.002 0,22.002 0,26.002 4,26.002 4,30 8,30 8,26.002 12,26.002 12,22.002 8,22.002     \"></polygon> <polygon fill=\"#90a4ae\" points=\"8,36 4,36 4,40 0,40 0,44 4,44 4,48 8,48 8,44 12,44 12,40 8,40  \"></polygon> <path d=\"M48,39.272v-4.574h-2.136c-0.256-1-0.67-1.935-1.226-2.771l1.434-1.433l-2.598-2.598l-1.431,1.434   c-0.832-0.552-1.761-0.964-2.756-1.221v-2.141h-4.607v2.141c-1.015,0.262-1.967,0.687-2.813,1.255l-1.373-1.373l-2.595,2.596   l1.396,1.396c-0.533,0.817-0.935,1.729-1.186,2.698h-2.139v4.607h2.139c0.257,0.993,0.669,1.926,1.221,2.758l-1.431,1.431   l2.595,2.596l1.431-1.434c0.837,0.556,1.77,0.968,2.765,1.226V48h4.59v-2.136c0.974-0.251,1.888-0.654,2.707-1.188l1.488,1.488   l2.598-2.595l-1.468-1.468c0.573-0.852,0.998-1.808,1.26-2.829H48z M36.984,40.762c-2.085,0-3.774-1.69-3.774-3.777   c0-2.085,1.689-3.774,3.774-3.774s3.777,1.689,3.777,3.774C40.762,39.071,39.069,40.762,36.984,40.762z\" fill=\"#90a4ae\"></path> <path d=\"M16,39v6h11.046c-1.369-1.696-2.303-3.751-2.661-6H16z\" fill=\"#90a4ae\"></path> <path d=\"M36.986,24c1.04,0,2.046,0.138,3.014,0.373V21H16v6h12.769C30.99,25.13,33.855,24,36.986,24z\" fill=\"#90a4ae\"></path></g></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
