// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package icons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SpentIcon() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg id=\"glyph\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" fill=\"#90a4ae\" width=\"15\" height=\"15\"><title>Money</title><path d=\"M53.62,23.87H12.64V46.3H58V23.87ZM17.26,45.35a3.31022,3.31022,0,0,1,.0001-6.62A3.31022,3.31022,0,0,1,17.26,45.35Zm20.26-8.53a2.86475,2.86475,0,0,1-2.49,2.66v.96a1,1,0,0,1-2,0v-.9h-1.1a1.0002,1.0002,0,0,1,.00007-2H34.35c.67,0,1.17-.38,1.17-.72v-.57c.0244-.44047-.77437-.80787-1.42007-.72993-3.47354.01587-4.40694-4.24477-1.06982-5.2801L33.03,28.96a1,1,0,0,1,2,0v1.12H36.4a1,1,0,1,1,0,2H34.1c-1.53018.048-1.53005,1.39225,0,1.44A3.02422,3.02422,0,0,1,37.52,36.82Zm15.74-5.47a3.31022,3.31022,0,0,1,.0001-6.62A3.31022,3.31022,0,0,1,53.26,31.35Z\"></path> <path d=\"M53.26,26.73a1.31014,1.31014,0,0,0,.00006,2.62A1.31014,1.31014,0,0,0,53.26,26.73Z\"></path> <path d=\"M46.97,21.87h2.58A1.30316,1.30316,0,0,0,46.97,21.87Z\"></path> <path d=\"M48.26,18.73a3.306,3.306,0,0,1,3.3,3.14h.86V18.29H6V40.11h4.64v-.78a3.30926,3.30926,0,1,1-.37992-6.6c.12992,0,.24992.01.37992.02V22.87a.99655.99655,0,0,1,1-1H44.96A3.306,3.306,0,0,1,48.26,18.73Z\"></path> <path d=\"M8.95,36.04a1.31287,1.31287,0,0,0,1.69,1.25l0-2.5A1.31292,1.31292,0,0,0,8.95,36.04Z\"></path> <path d=\"M17.26,40.73a1.31014,1.31014,0,0,0,.00006,2.62A1.31014,1.31014,0,0,0,17.26,40.73Z\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

//.fil0 { stroke:#90a4ae }
