GET /api/v1/budgets
Host: localhost:8080
x-access-token: {{TOKEN}}

POST /api/v1/budgets
Host: localhost:8080
x-access-token: {{TOKEN}}
Content-Type: application/json

{
    "project_id": "0a91affc-7eb7-4973-8f80-e90f60c48cf0",
    "budget_item_id": "cfb78774-c958-47fa-a760-2d6a7bce06cd",
    "quantity": 256,
    "cost": 5.3
}

GET /api/v1/budgets/0a91affc-7eb7-4973-8f80-e90f60c48cf0
Host: localhost:8080
x-access-token: {{TOKEN}}
