GET /api/v1/invoices
Host: localhost:8080
x-access-token: {{TOKEN}}

POST /api/v1/invoices
Host: localhost:8080
x-access-token: {{TOKEN}}

{
     "supplier_id": "64bdc016-57bb-4ef5-84fe-0eb60a48b5a7",
     "project_id": "37791b10-dae8-44e4-8b98-9722731f037a",
     "invoice_number": "123456789",
     "invoice_date": "2022-12-31T12:00:00Z"
}

GET /api/v1/invoices/96e15cb8-8f3a-4199-b355-26198a87c155
Host: localhost:8080
x-access-token: {{TOKEN}}

PUT /api/v1/invoices/96e15cb8-8f3a-4199-b355-26198a87c155
Host: localhost:8080
x-access-token: {{TOKEN}}

{
     "supplier_id": "5d3e0a27-94d5-4fd7-a35e-a8a600bf4bbd",
     "invoice_number": "123456790",
     "invoice_date": "2022-12-31T12:00:00Z",
     "total": 153
}

DELETE /api/v1/invoices/96e15cb8-8f3a-4199-b355-26198a87c155
Host: localhost:8080
x-access-token: {{TOKEN}}
