GET /api/v1/projects
Host: localhost:8080
x-access-token: {{TOKEN}}

POST /api/v1/projects
Host: localhost:8080
x-access-token: {{TOKEN}}

{
     "name": "TEST PROJECT"
}

GET /api/v1/projects/0a91affc-7eb7-4973-8f80-e90f60c48cf0
Host: localhost:8080
x-access-token: {{TOKEN}}

PUT /api/v1/projects/0a91affc-7eb7-4973-8f80-e90f60c48cf0
Host: localhost:8080
x-access-token: {{TOKEN}}

{
     "name": "TEST PROJECT",
     "is_active": true
}
