GET /api/v1/users
Host: http://0.0.0.0:8080
x-access-token: 


POST /api/v1/users
Host: http://0.0.0.0:8080
x-access-token:

{
     "email": "test3@test.com",
     "password": "password123",
     "name": "test",
     "role_id" : "a"
}
