name: Integration Tests

on: pull_request

jobs:
  unit-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Run integration tests
        run: make integration-test
